# Collaborators can publish a new version of what's on master via "workflow_dispatch"
# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

name: Publish

on:
  workflow_dispatch:
    inputs:
      Version:
        description: "Version, anything accepted by `npm version XXX`"
        required: true

jobs:
  NPM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm version ${{ github.event.inputs.Version }}
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - run: git push --follow-tags

  Release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - uses: notlmn/release-with-changelog@v1
      with:
        include-hash: true
        include-range: true
      env:
        RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
